### PR TITLE
Remove default queries

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>

### CODE REVIEW

**Comment by kuba--** [comment]
Closes https://github.com/src-d/regression-gitbase/issues/7

**Review by jfontan — APPROVED** [review]

**Comment by jfontan** [comment]
The test won't pass until reading `regression.yaml` is fixed. I'm on it.

**Review by erizocosmico — APPROVED** [review]

**Comment by jfontan** [comment]
@kuba--, can you rebase? The changes to fix the test should be there.

**Comment by kuba--** [comment]
@jfontan - rebased.

**Comment by jfontan** [comment]
Thanks @kuba-- !

**Pull request merged**
