### PR TITLE
Update golang version on Dockerfile

### PR DESCRIPTION
**Pull request by ajnavarro**
Signed-off-by: Antonio Navarro Perez <antnavper@gmail.com>

### CODE REVIEW

**Review by jfontan — APPROVED** [review]

**Review by erizocosmico — APPROVED** [review]
LGTM but CI fails

**Comment by kuba--** [comment]
looks that we should switch to go modules for this repo, as well.
It fails because it can't find: `github.com/bblfsh/go-client/v4`

**Comment by ajnavarro** [comment]
Related: https://github.com/src-d/regression-core/

**Comment by ajnavarro** [comment]
outdated

**Pull request closed without merging**
